name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  FOUNDRY_PROFILE: ci

jobs:
  build-and-test:
    strategy:
      fail-fast: true

    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Cache Foundry installation
        uses: actions/cache@v4
        with:
          path: ~/.foundry
          key: foundry-${{ runner.os }}-${{ hashFiles('**/foundry.toml') }}
          restore-keys: |
            foundry-${{ runner.os }}-

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Show Forge version
        run: forge --version

      - name: Run Forge fmt
        run: forge fmt --check
        id: fmt

      - name: Run Forge build
        run: forge build --sizes
        id: build

      - name: Run Forge tests
        run: forge test -vvv
        id: test

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: forge-build
          path: out/  # Adjust if Foundry outputs to a different directory
          retention-days: 1

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/main'  # Change if default branch differs
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Restore Foundry installation
        uses: actions/cache@v4
        with:
          path: ~/.foundry
          key: foundry-${{ runner.os }}-${{ hashFiles('**/foundry.toml') }}
          restore-keys: |
            foundry-${{ runner.os }}-

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: forge-build
          path: out/

      - name: Deploy
        run: |
          forge script script/Counter.s.sol:CounterScript --rpc-url ${{ secrets.RPC_URL }} --private-key ${{ secrets.PK }} --broadcast
        id: deploy

      - name: Archive Deploy Report
        uses: actions/upload-artifact@v4
        with:
          name: deploy-report
          path: broadcast/**/*.json